version: '3'
services:
  webserver:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
